import React from 'react';
import Head from 'next/head'
import Temperatura from './LineChartTemperatura.jsx'
import Humedad from './LineChartHumedad'
import styles from '@/styles/Home.module.css'
import Menu from './components/Menu.jsx'
import Busqueda from './components/Busqueda'
import { Fredoka } from 'next/font/google'

const fredoka = Fredoka({ subsets: ['latin'], weight: '300', width: 110 })

export default function Example({ data }) {
  return (
    
    <div className={styles.body}>
      
      <Head>
        <title> B.A.T </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/LogoB.png/"/>
      </Head> 

      <div style={fredoka.style} className={styles.header}>

        <div className={styles.left}>
          <a href="" className={styles.menu} ><Menu width={24} height={23}/></a>
          <a href=""> <img className={styles.logo} src="logo-datos.png" /></a>
        </div>
          
        <div className={styles.center}>
          <a className={styles.nos} href="">NOSOTROS</a>
          <a className={styles.cont} href="">CONTACTO</a>
          <a className={styles.sub} href="">SUBSCRIPCIÓN</a>
        </div>
          
        <div className={styles.right}>
          <a className={styles.log} href="">Log In</a>
          <a href="" className={styles.lupa}><Busqueda width={24} height={23}/></a>
        </div>

      </div>

      <div className={styles.datos}>
        {
          <div className={styles.resu}>

            <h2 style={fredoka.style} className={styles.titulo}> RESULTADOS DE TRAZABILIDAD</h2>

            <div className={styles.izquierda}>

              <ul className={styles.list}>
                <li className={styles.item}>
                  <div className={styles.cardRegistro}>
                    <p style={fredoka.style} className={styles.tituloRegistro}>Numero de registro</p>
                    <p style={fredoka.style} className={styles.textoRegistro}>N°1</p>
                    <img className={styles.soleado} src="soleado.png" alt="" />
                  </div>
                </li>

                <li className={styles.item}>
                  <div className={styles.cardGps}>
                    <p style={fredoka.style} className={styles.tituloGps}>Ubicación</p>
                    <p style={fredoka.style} className={styles.textoLatitud}>Latitud: {data.ubicacion.latitud}</p>
                    <p style={fredoka.style} className={styles.textoLongitud}>Longitud: {data.ubicacion.longitud} </p>
                    <img className={styles.gps} src="ubicacion.png" alt="" />
                  </div>
                </li>

                <li className={styles.item}>
                  <div className={styles.cardTiempo}>
                    <p style={fredoka.style} className={styles.tituloTiempo}>Tiempo de medición</p>
                    <p style={fredoka.style} className={styles.textoTiempo}>11:00</p>
                    <img className={styles.reloj} src="reloj-de-pared-2.png" alt="" />
                  </div>
                </li>
              </ul>

            </div>

          </div>
        }
      </div> 
        
      <div>
        <Temperatura
          data = {data.temperatura}
          labels = {data.time} 
        />
        <Humedad
          data = {data.humedad}
          labels = {data.time}
        />
      </div>
      
        
        
    </div>
    
  )
}

export const getServerSideProps = async (context) => {
  const options = { method: 'GET' };
  const res = await fetch("https://next-app-api.vercel.app/api/camiones/caba-lp/sensores", options)
  const datos = await res.json()

  let humedad = [] 
  let temperatura = [] 
  let time = []
  for (const obj of datos) {
    humedad.push(obj.humedad)
    temperatura.push(obj.temperatura)
    let date = new Date(obj.tiempoMedicion)
    let hours = date.getHours()
    let minutes = date.getMinutes() === 0 ? "00" : date.getMinutes()
    time.push(hours + ':' + minutes)
  }  
  return {
    props: {
      data: { humedad: humedad, temperatura: temperatura, time: time, ubicacion: { latitud:datos[0].latitud, longitud:datos[0].longitud } }
    
    }
  }
}


