import React from 'react';
import Head from 'next/head'
import Temperatura from './LineChartTemperatura.jsx'
import Humedad from './LineChartHumedad'
import styles from '@/styles/Home.module.css'
import Menu from './components/Menu.jsx'
import Busqueda from './components/Busqueda'
import { Inter, Fredoka } from 'next/font/google'

const fredoka = Fredoka({ subsets: ['latin'], weight: '500' })

export default function Example() {
  return (
    <>
    <div className={styles.body}>
      
      <Head>
        <title> B.A.T </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/LogoB.png"/> 
      </Head> 

      <div style={fredoka.style} className={styles.header}>

        <div className={styles.left}>
          <a href=""><Menu width={24} height={23}/></a>
          <a href=""> <img className={styles.logo} src="logo-datos.png"/></a>
        </div>
        <div className={styles.center}>
          <a className={styles.nos} href="">NOSOTROS</a>
          <a className={styles.cont} href="">CONTACTO</a>
          <a className={styles.sub} href="">SUBSCRIPCIÓN</a>
        </div>
        <div className={styles.right}>
          <a className={styles.log} href="">Log In</a>
          <a href="" className={styles.lupa}><Busqueda width={24} height={23}/></a>
        </div>

      </div>
      
      
        <div>
          <Temperatura />
          <Humedad />
        </div>



    </div>






    </>
  )
}


